# Generated by Django 6.0.4 on 2026-09-12 18:40

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioDobleFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_hash', models.CharField(max_length=255)),
                ('proveedor', models.CharField(choices=[('PASSWORD', 'Password'), ('GOOGLE', 'Google'), ('INVITACION', 'Invitacion')], default='PASSWORD', max_length=20)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('expira_en', models.DateTimeField(default=accounts.models.default_two_factor_expiry)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_doble_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionAdminPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre_sugerido', models.CharField(blank=True, max_length=180, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('REVOCADA', 'Revocada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('expira_en', models.DateTimeField(default=accounts.models.default_invitation_expiry)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('invitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_admin_plataforma_emitidas', to=settings.AUTH_USER_MODEL)),
                ('user_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_admin_plataforma_aceptadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembresiaCapaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OWNER_ADMIN', 'Owner admin'), ('OPERADOR', 'Operador'), ('CONSULTA', 'Consulta')], default='OWNER_ADMIN', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('invitacion_aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_acceso', to='empresas.capanegocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_capa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['capa_negocio__nombre', 'user__email', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre_sugerido', models.CharField(blank=True, max_length=180, null=True)),
                ('rol', models.CharField(choices=[('OWNER_ADMIN', 'Owner admin'), ('OPERADOR', 'Operador'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('REVOCADA', 'Revocada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('expira_en', models.DateTimeField(default=accounts.models.default_invitation_expiry)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_acceso', to='empresas.capanegocio')),
                ('invitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('membership_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_origen', to='accounts.membresiacapanegocio')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecuperacionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('expira_en', models.DateTimeField(default=accounts.models.default_password_reset_expiry)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proveedor', models.CharField(choices=[('PASSWORD', 'Password'), ('GOOGLE', 'Google'), ('BOOTSTRAP', 'Bootstrap')], default='PASSWORD', max_length=20)),
                ('refresh_expires_at', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ultimo_uso', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mostrado', models.CharField(blank=True, max_length=180, null=True)),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('es_admin_plataforma', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=120)),
                ('recurso_tipo', models.CharField(max_length=120)),
                ('recurso_id', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
                ('capa_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['capa_negocio', '-fecha_creacion', '-id'], name='idx_audit_capa_fecha'), models.Index(fields=['capa_negocio', 'accion', '-fecha_creacion'], name='idx_audit_capa_acc_fecha'), models.Index(fields=['capa_negocio', 'recurso_tipo', 'recurso_id'], name='idx_audit_capa_recurso')],
            },
        ),
        migrations.AddIndex(
            model_name='membresiacapanegocio',
            index=models.Index(fields=['user', 'activo', 'capa_negocio'], name='idx_member_user_active'),
        ),
        migrations.AddIndex(
            model_name='membresiacapanegocio',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_member_capa_active'),
        ),
        migrations.AddConstraint(
            model_name='membresiacapanegocio',
            constraint=models.UniqueConstraint(fields=('user', 'capa_negocio'), name='unique_membership_user_capa'),
        ),
        migrations.AddIndex(
            model_name='invitacionacceso',
            index=models.Index(fields=['email', 'estatus', 'expira_en'], name='idx_inv_email_status'),
        ),
        migrations.AddIndex(
            model_name='invitacionacceso',
            index=models.Index(fields=['capa_negocio', 'email', 'estatus'], name='idx_inv_capa_email'),
        ),
    ]
