"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""
import environ
import os
import dj_database_url
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar django-environ
env = environ.Env()
# Leer variables locales si existen (en producción usa el entorno del proceso).
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default="django-insecure-^(ilb=@w#1@l98#pm2$2qqed!27&diy-yern%u5z*)fh&#8lz(")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)
APP_ENV = env('APP_ENV', default='development')
IS_PRODUCTION = APP_ENV.strip().lower() in {'production', 'prod'} or bool(
    os.environ.get('RENDER')
)
DEMO_MODE = env.bool('DEMO_MODE', default=False)
DISABLE_OUTBOUND_INTEGRATIONS = env.bool(
    'DISABLE_OUTBOUND_INTEGRATIONS',
    default=DEMO_MODE,
)
OUTBOUND_WHATSAPP_ALLOWED_NUMBERS = env.list(
    'OUTBOUND_WHATSAPP_ALLOWED_NUMBERS',
    default=[],
)
COBRANZA_TEST_LAB_ENABLED = env.bool(
    'COBRANZA_TEST_LAB_ENABLED',
    default=True,
)
COBRANZA_TEST_LAB_ALLOWED_EMAILS = env.list(
    'COBRANZA_TEST_LAB_ALLOWED_EMAILS',
    default=['01.agodinez@gmail.com'],
)
COBRANZA_TEST_LAB_ALLOWED_CAPAS = env.list(
    'COBRANZA_TEST_LAB_ALLOWED_CAPAS',
    default=['Maya Coliving'],
)
LOCK_TENANT_MESSAGE_TEMPLATES = env.bool(
    'LOCK_TENANT_MESSAGE_TEMPLATES',
    default=False,
)
REQUIRE_WHATSAPP_SHARED_NUMBER_AGREEMENT = env.bool(
    'REQUIRE_WHATSAPP_SHARED_NUMBER_AGREEMENT',
    default=True,
)
COLLECTION_REQUIRE_CONSENT_FOR_WHATSAPP = env.bool(
    'COLLECTION_REQUIRE_CONSENT_FOR_WHATSAPP',
    default=IS_PRODUCTION,
)
PORTAL_OTP_REQUIRED = env.bool(
    'PORTAL_OTP_REQUIRED',
    default=True,
)
PORTAL_OTP_WHATSAPP_TEMPLATE_NAME = env(
    'PORTAL_OTP_WHATSAPP_TEMPLATE_NAME',
    default='betterp_portal_otp',
)
PORTAL_OTP_WHATSAPP_TEMPLATE_LANGUAGE = env(
    'PORTAL_OTP_WHATSAPP_TEMPLATE_LANGUAGE',
    default='es_MX',
)
PORTAL_OTP_EXPIRATION_MINUTES = env.int(
    'PORTAL_OTP_EXPIRATION_MINUTES',
    default=10,
)
PORTAL_OTP_RESEND_SECONDS = env.int(
    'PORTAL_OTP_RESEND_SECONDS',
    default=60,
)
PORTAL_OTP_MAX_ATTEMPTS = env.int(
    'PORTAL_OTP_MAX_ATTEMPTS',
    default=5,
)
PORTAL_SESSION_HOURS = env.int(
    'PORTAL_SESSION_HOURS',
    default=24,
)
PLAN_LIMIT_EXEMPT_CAPAS = env.list(
    'PLAN_LIMIT_EXEMPT_CAPAS',
    default=['Maya Coliving'],
)

ALLOWED_HOSTS = env.list(
    'ALLOWED_HOSTS',
    default=[
        'api.betterp.net',
        'app.betterp.net',
        'betterp.net',
        'www.betterp.net',
        '.betterp.net',
        'localhost',
        '127.0.0.1',
        'testserver',
    ],
)

# Application definition
INSTALLED_APPS = [
    'corsheaders',  # <--- CORS
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'storages',
    # --- Tus nuevas Apps ---
    'accounts',
    'billing',
    'empresas',
    'crm',
    'finanzas',
    'comunicaciones',
    'facturacion',
    'catalogo',
    'pos',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestMonitoringMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
DATABASES = {
    'default': dj_database_url.config(
        # Ahora lee la URL usando django-environ
        default=env('DATABASE_URL', default=''),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

REDIS_URL = env('REDIS_URL', default='')
CACHE_KEY_PREFIX = env('CACHE_KEY_PREFIX', default='betterp')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': CACHE_KEY_PREFIX,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': env.bool('REDIS_IGNORE_EXCEPTIONS', default=True),
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': f'{CACHE_KEY_PREFIX}-local-cache',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
PASSWORD_ARGON2_TIME_COST = env.int("PASSWORD_ARGON2_TIME_COST", default=2)
PASSWORD_ARGON2_MEMORY_COST = env.int("PASSWORD_ARGON2_MEMORY_COST", default=19456)
PASSWORD_ARGON2_PARALLELISM = env.int("PASSWORD_ARGON2_PARALLELISM", default=1)
PASSWORD_HASHERS = [
    "accounts.hashers.BetterPArgon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ==========================================
# Configuración Global de Cloudflare R2 (S3)
# ==========================================
# Mapeamos las variables de tu .env (R2_...) a las que necesita django-storages
AWS_ACCESS_KEY_ID = env('R2_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('R2_SECRET_ACCESS_KEY', default='')
AWS_S3_ENDPOINT_URL = env('R2_ENDPOINT_URL', default='')
AWS_S3_SIGNATURE_VERSION = env('AWS_S3_SIGNATURE_VERSION', default='s3v4')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='auto')
AWS_S3_ADDRESSING_STYLE = env('AWS_S3_ADDRESSING_STYLE', default='path')
AWS_STORAGE_BUCKET_NAME = "betterp-storage" 
R2_BACKUP_BUCKET_NAME = env('R2_BACKUP_BUCKET_NAME', default=AWS_STORAGE_BUCKET_NAME)
R2_BACKUP_PREFIX = env('R2_BACKUP_PREFIX', default='backups')
BACKUP_RETENTION_DAYS = env.int('BACKUP_RETENTION_DAYS', default=180)
REQUEST_LOGGING_ENABLED = env.bool("REQUEST_LOGGING_ENABLED", default=True)
REQUEST_LOGGING_SLOW_MS = env.int("REQUEST_LOGGING_SLOW_MS", default=1500)
REQUEST_METRICS_ENABLED = env.bool("REQUEST_METRICS_ENABLED", default=True)
REQUEST_METRICS_SLOW_MS = env.int(
    "REQUEST_METRICS_SLOW_MS",
    default=REQUEST_LOGGING_SLOW_MS,
)
CATALOGO_INTERNAL_API_TOKEN = env("CATALOGO_INTERNAL_API_TOKEN", default="")
CATALOGO_SERVICE_BASE_URL = env("CATALOGO_SERVICE_BASE_URL", default="")
CATALOGO_SERVICE_INTERNAL_KEY = env("CATALOGO_SERVICE_INTERNAL_KEY", default="")
CATALOGO_APP_BASE_URL = env(
    "CATALOGO_APP_BASE_URL",
    default="https://vendefacil.betterp.net",
)
CATALOGO_SERVICE_TIMEOUT_SECONDS = env.int(
    "CATALOGO_SERVICE_TIMEOUT_SECONDS",
    default=8,
)
TIENDA_FACIL_APP_BASE_URL = env(
    "TIENDA_FACIL_APP_BASE_URL",
    default="https://tiendafacil.betterp.net",
)
TIENDA_FACIL_SERVICE_BASE_URL = env(
    "TIENDA_FACIL_SERVICE_BASE_URL",
    default="https://api-tiendafacil.betterp.net",
)
TIENDA_FACIL_SERVICE_INTERNAL_KEY = env("TIENDA_FACIL_SERVICE_INTERNAL_KEY", default="")
TIENDA_FACIL_CAPA_ALIASES = env("TIENDA_FACIL_CAPA_ALIASES", default="")
SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=0.0)
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            environment=APP_ENV,
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,
        )
    except ImportError:
        pass
LOG_LEVEL = env("LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "betterp.requests": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

if AWS_ACCESS_KEY_ID:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Permitir que cualquier página web (como nuestro Next.js) consulte esta API
CORS_ALLOW_ALL_ORIGINS = env.bool(
    'CORS_ALLOW_ALL_ORIGINS',
    default=bool(DEBUG and not IS_PRODUCTION),
)
CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=[
        'https://app.betterp.net',
        'https://betterp.net',
        'https://www.betterp.net',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)
CORS_ALLOW_CREDENTIALS = env.bool('CORS_ALLOW_CREDENTIALS', default=True)
CORS_ALLOW_HEADERS = (*default_headers, "x-betterp-capa-id", "x-portal-session")
CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'https://app.betterp.net',
        'https://api.betterp.net',
        'https://betterp.net',
        'https://www.betterp.net',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = env.int(
    'SECURE_HSTS_SECONDS',
    default=31536000 if IS_PRODUCTION else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_REFERRER_POLICY = env('SECURE_REFERRER_POLICY', default='same-origin')
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env('SESSION_COOKIE_SAMESITE', default='Lax')
CSRF_COOKIE_SAMESITE = env('CSRF_COOKIE_SAMESITE', default='Lax')
X_FRAME_OPTIONS = 'DENY'

BETTERP_PUBLIC_BASE_URL = env('BETTERP_PUBLIC_BASE_URL', default='https://betterp.net').rstrip('/')
LEGACY_BETTERP_APP_BASE_URL = 'https://app.betterp.net'
BETTERP_PLATFORM_BASE_URL = env(
    'BETTERP_PLATFORM_BASE_URL',
    default=BETTERP_PUBLIC_BASE_URL,
).rstrip('/')
if BETTERP_PLATFORM_BASE_URL.lower() == LEGACY_BETTERP_APP_BASE_URL:
    BETTERP_PLATFORM_BASE_URL = BETTERP_PUBLIC_BASE_URL


def _normalize_frontend_base_url(value):
    base_url = (value or '').strip().rstrip('/')
    if base_url.lower() == LEGACY_BETTERP_APP_BASE_URL:
        return BETTERP_PLATFORM_BASE_URL
    return base_url


FRONTEND_BASE_URL = _normalize_frontend_base_url(
    env('FRONTEND_BASE_URL', default='http://localhost:3000')
)
BACKEND_PUBLIC_BASE_URL = env('BACKEND_PUBLIC_BASE_URL', default='')
MERCADO_LIBRE_CLIENT_ID = env('MERCADO_LIBRE_CLIENT_ID', default='')
MERCADO_LIBRE_CLIENT_SECRET = env('MERCADO_LIBRE_CLIENT_SECRET', default='')
MERCADO_LIBRE_REDIRECT_URI = env('MERCADO_LIBRE_REDIRECT_URI', default='')
MERCADO_LIBRE_DEFAULT_CATEGORY_ID = env('MERCADO_LIBRE_DEFAULT_CATEGORY_ID', default='')
MERCADO_LIBRE_DEFAULT_LISTING_TYPE_ID = env(
    'MERCADO_LIBRE_DEFAULT_LISTING_TYPE_ID',
    default='',
)
EASYBROKER_API_BASE_URL = env('EASYBROKER_API_BASE_URL', default='')
EASYBROKER_STAGING_API_BASE_URL = env('EASYBROKER_STAGING_API_BASE_URL', default='')
EASYBROKER_API_KEY = env('EASYBROKER_API_KEY', default='')
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_RENTAL_COPY_MODEL = env('OPENAI_RENTAL_COPY_MODEL', default='gpt-5.5')
OPENAI_MARKETING_CONTENT_MODEL = env('OPENAI_MARKETING_CONTENT_MODEL', default=OPENAI_RENTAL_COPY_MODEL)
OPENAI_MARKETING_CONTENT_ENABLED = env.bool('OPENAI_MARKETING_CONTENT_ENABLED', default=True)
BETTERP_COMMERCE_MARKETING_BRIDGE_ENABLED = env.bool(
    'BETTERP_COMMERCE_MARKETING_BRIDGE_ENABLED',
    default=False,
)
BETTERP_COMMERCE_MARKETING_IMPORT_ENABLED = env.bool(
    'BETTERP_COMMERCE_MARKETING_IMPORT_ENABLED',
    default=False,
)
BETTERP_COMMERCE_MARKETING_PUBLISH_ENABLED = env.bool(
    'BETTERP_COMMERCE_MARKETING_PUBLISH_ENABLED',
    default=False,
)
BETTERP_COMMERCE_MARKETING_ROLLOUT_ENABLED = env.bool(
    'BETTERP_COMMERCE_MARKETING_ROLLOUT_ENABLED',
    default=False,
)
BETTERP_COMMERCE_MARKETING_ROLLOUT_MODE = env(
    'BETTERP_COMMERCE_MARKETING_ROLLOUT_MODE',
    default='rollback',
)
BETTERP_COMMERCE_MARKETING_CANARY_SCOPES = env(
    'BETTERP_COMMERCE_MARKETING_CANARY_SCOPES',
    default='',
)
BETTERP_COMMERCE_MARKETING_ROLLBACK_SAFE = env.bool(
    'BETTERP_COMMERCE_MARKETING_ROLLBACK_SAFE',
    default=True,
)
BETTERP_COMMERCE_MARKETING_MIN_OBSERVATION_HOURS = env.int(
    'BETTERP_COMMERCE_MARKETING_MIN_OBSERVATION_HOURS',
    default=24,
)
BETTERP_COMMERCE_MARKETING_VERIFY_KEYS = env(
    'BETTERP_COMMERCE_MARKETING_VERIFY_KEYS',
    default='',
)
BETTERP_COMMERCE_MARKETING_ALLOWED_CLOCK_SKEW_SECONDS = env.int(
    'BETTERP_COMMERCE_MARKETING_ALLOWED_CLOCK_SKEW_SECONDS',
    default=60,
)
BETTERP_COMMERCE_MARKETING_TIMEOUT_SECONDS = env.float(
    'BETTERP_COMMERCE_MARKETING_TIMEOUT_SECONDS',
    default=8.0,
)
OPENAI_MARKETING_CONTENT_REQUEST_TIMEOUT_SECONDS = env.float(
    'OPENAI_MARKETING_CONTENT_REQUEST_TIMEOUT_SECONDS',
    default=8.0,
)
OPENAI_MARKETING_CONTENT_TOTAL_BUDGET_SECONDS = env.float(
    'OPENAI_MARKETING_CONTENT_TOTAL_BUDGET_SECONDS',
    default=24.0,
)
GOOGLE_API_KEY = env('GOOGLE_API_KEY', default='')
GOOGLE_VISION_API_KEY = env('GOOGLE_VISION_API_KEY', default='')
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
ACCESS_TOKEN_MAX_AGE_SECONDS = env.int(
    'ACCESS_TOKEN_MAX_AGE_SECONDS',
    default=60 * 60 * 8,
)
REFRESH_TOKEN_MAX_AGE_SECONDS = env.int(
    'REFRESH_TOKEN_MAX_AGE_SECONDS',
    default=60 * 60 * 24 * 30,
)
HEALTH_API_WARMUP_ENABLED = env.bool('HEALTH_API_WARMUP_ENABLED', default=True)
AUTH_RATE_LIMIT_LOGIN_ATTEMPTS = env.int('AUTH_RATE_LIMIT_LOGIN_ATTEMPTS', default=8)
AUTH_RATE_LIMIT_LOGIN_WINDOW_SECONDS = env.int(
    'AUTH_RATE_LIMIT_LOGIN_WINDOW_SECONDS',
    default=300,
)
AUTH_RATE_LIMIT_PASSWORD_RECOVERY_ATTEMPTS = env.int(
    'AUTH_RATE_LIMIT_PASSWORD_RECOVERY_ATTEMPTS',
    default=4,
)
AUTH_RATE_LIMIT_PASSWORD_RECOVERY_WINDOW_SECONDS = env.int(
    'AUTH_RATE_LIMIT_PASSWORD_RECOVERY_WINDOW_SECONDS',
    default=900,
)
AUTH_RATE_LIMIT_GOOGLE_ATTEMPTS = env.int('AUTH_RATE_LIMIT_GOOGLE_ATTEMPTS', default=12)
AUTH_RATE_LIMIT_GOOGLE_WINDOW_SECONDS = env.int(
    'AUTH_RATE_LIMIT_GOOGLE_WINDOW_SECONDS',
    default=300,
)
AUTH_RATE_LIMIT_REGISTRATION_ATTEMPTS = env.int(
    'AUTH_RATE_LIMIT_REGISTRATION_ATTEMPTS',
    default=5,
)
AUTH_RATE_LIMIT_REGISTRATION_WINDOW_SECONDS = env.int(
    'AUTH_RATE_LIMIT_REGISTRATION_WINDOW_SECONDS',
    default=900,
)
AUTH_RATE_LIMIT_TWO_FACTOR_ATTEMPTS = env.int(
    'AUTH_RATE_LIMIT_TWO_FACTOR_ATTEMPTS',
    default=6,
)
AUTH_RATE_LIMIT_TWO_FACTOR_WINDOW_SECONDS = env.int(
    'AUTH_RATE_LIMIT_TWO_FACTOR_WINDOW_SECONDS',
    default=600,
)
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_MODE = env('STRIPE_MODE', default='')
STRIPE_TEST_SECRET_KEY = env('STRIPE_TEST_SECRET_KEY', default='')
STRIPE_LIVE_SECRET_KEY = env('STRIPE_LIVE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_TEST_WEBHOOK_SECRET = env('STRIPE_TEST_WEBHOOK_SECRET', default='')
STRIPE_LIVE_WEBHOOK_SECRET = env('STRIPE_LIVE_WEBHOOK_SECRET', default='')
STRIPE_API_BASE_URL = env(
    'STRIPE_API_BASE_URL',
    default='https://api.stripe.com',
)
PUBLIC_TRIAL_REGISTRATION_ENABLED = env.bool(
    'PUBLIC_TRIAL_REGISTRATION_ENABLED',
    default=False,
)
FACTURAMA_SANDBOX_BASE_URL = env(
    'FACTURAMA_SANDBOX_BASE_URL',
    default='https://apisandbox.facturama.mx',
)
FACTURAMA_SANDBOX_USERNAME = env('FACTURAMA_SANDBOX_USERNAME', default='')
FACTURAMA_SANDBOX_PASSWORD = env('FACTURAMA_SANDBOX_PASSWORD', default='')
FACTURAMA_PRODUCTION_BASE_URL = env(
    'FACTURAMA_PRODUCTION_BASE_URL',
    default='https://api.facturama.mx',
)
FACTURAMA_PRODUCTION_USERNAME = env('FACTURAMA_PRODUCTION_USERNAME', default='')
FACTURAMA_PRODUCTION_PASSWORD = env('FACTURAMA_PRODUCTION_PASSWORD', default='')
FACTURAMA_TIMEOUT_SECONDS = env.int('FACTURAMA_TIMEOUT_SECONDS', default=20)
FACTURACION_ENCRYPTION_KEY = env('FACTURACION_ENCRYPTION_KEY', default=SECRET_KEY)
BETTERP_BILLING_CAPA_ID = env.int('BETTERP_BILLING_CAPA_ID', default=0)
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@betterp.local')
SERVER_EMAIL = env('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)
RESEND_API_BASE_URL = env('RESEND_API_BASE_URL', default='https://api.resend.com')
RESEND_API_KEY = env('RESEND_API_KEY', default='')
RESEND_WEBHOOK_SECRET = env('RESEND_WEBHOOK_SECRET', default='')
RESEND_FROM_EMAIL = env('RESEND_FROM_EMAIL', default='')
RESEND_FROM_NAME = env('RESEND_FROM_NAME', default='BettERP')
RESEND_REPLY_TO = env('RESEND_REPLY_TO', default='')
RESEND_VERIFIED_DOMAIN = env('RESEND_VERIFIED_DOMAIN', default='')
SALES_CONTACT_EMAIL = env('SALES_CONTACT_EMAIL', default='contacto@betterp.net')
BETTERP_MARKETING_BASE_URL = env('BETTERP_MARKETING_BASE_URL', default=BETTERP_PUBLIC_BASE_URL)
BETTERP_EMAIL_LOGO_URL = env('BETTERP_EMAIL_LOGO_URL', default='')
BETTERP_LEGAL_NAME = env('BETTERP_LEGAL_NAME', default='BetterP')
BETTERP_SALES_NOTIFY_EMAIL = env('BETTERP_SALES_NOTIFY_EMAIL', default='')
BETTERP_OPERATIONS_NOTIFY_EMAIL = env('BETTERP_OPERATIONS_NOTIFY_EMAIL', default='')
INBOUND_EMAIL_IMAP_ENABLED = env.bool('INBOUND_EMAIL_IMAP_ENABLED', default=False)
INBOUND_EMAIL_IMAP_HOST = env('INBOUND_EMAIL_IMAP_HOST', default='')
INBOUND_EMAIL_IMAP_PORT = env.int('INBOUND_EMAIL_IMAP_PORT', default=993)
INBOUND_EMAIL_IMAP_USERNAME = env('INBOUND_EMAIL_IMAP_USERNAME', default='')
INBOUND_EMAIL_IMAP_PASSWORD = env('INBOUND_EMAIL_IMAP_PASSWORD', default='')
INBOUND_EMAIL_IMAP_USE_SSL = env.bool('INBOUND_EMAIL_IMAP_USE_SSL', default=True)
INBOUND_EMAIL_IMAP_FOLDER = env('INBOUND_EMAIL_IMAP_FOLDER', default='INBOX')
INBOUND_EMAIL_IMAP_BATCH_SIZE = env.int('INBOUND_EMAIL_IMAP_BATCH_SIZE', default=25)
RESEND_WEBHOOK_TOLERANCE_SECONDS = env.int(
    'RESEND_WEBHOOK_TOLERANCE_SECONDS',
    default=300,
)
WHATSAPP_CLOUD_API_BASE_URL = env(
    'WHATSAPP_CLOUD_API_BASE_URL',
    default='https://graph.facebook.com',
)
WHATSAPP_CLOUD_API_VERSION = env(
    'WHATSAPP_CLOUD_API_VERSION',
    default='v22.0',
)
WHATSAPP_META_APP_ID = env('WHATSAPP_META_APP_ID', default='')
WHATSAPP_META_APP_SECRET = env('WHATSAPP_META_APP_SECRET', default='')
WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID = env(
    'WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID',
    default='',
)
WHATSAPP_WEBHOOK_VERIFY_TOKEN = env('WHATSAPP_WEBHOOK_VERIFY_TOKEN', default='')
WHATSAPP_WEBHOOK_PROCESS_INLINE = env.bool(
    'WHATSAPP_WEBHOOK_PROCESS_INLINE',
    default=True,
)
META_GRAPH_API_BASE_URL = env(
    'META_GRAPH_API_BASE_URL',
    default='https://graph.facebook.com',
)
META_GRAPH_API_VERSION = env(
    'META_GRAPH_API_VERSION',
    default='v25.0',
)
BACKOFFICE_META_APP_ID = env('BACKOFFICE_META_APP_ID', default='')
BACKOFFICE_META_APP_SECRET = env('BACKOFFICE_META_APP_SECRET', default='')
BACKOFFICE_META_REDIRECT_URI = env('BACKOFFICE_META_REDIRECT_URI', default='')
META_CLIENT_ID = env('META_CLIENT_ID', default='')
META_CLIENT_SECRET = env('META_CLIENT_SECRET', default='')
META_APP_ID = env(
    'META_APP_ID',
    default=BACKOFFICE_META_APP_ID or META_CLIENT_ID or env('WHATSAPP_META_APP_ID', default=''),
)
META_APP_SECRET = env(
    'META_APP_SECRET',
    default=BACKOFFICE_META_APP_SECRET or META_CLIENT_SECRET or env('WHATSAPP_META_APP_SECRET', default=''),
)
META_REDIRECT_URI = env('META_REDIRECT_URI', default=BACKOFFICE_META_REDIRECT_URI)
MARKETING_META_CLIENT_ID = env('MARKETING_META_CLIENT_ID', default='')
MARKETING_META_CLIENT_SECRET = env('MARKETING_META_CLIENT_SECRET', default='')
FACEBOOK_CLIENT_ID = env('FACEBOOK_CLIENT_ID', default='')
FACEBOOK_CLIENT_SECRET = env('FACEBOOK_CLIENT_SECRET', default='')
MARKETING_META_REDIRECT_URI = env('MARKETING_META_REDIRECT_URI', default='')
MARKETING_INSTAGRAM_CLIENT_ID = env('MARKETING_INSTAGRAM_CLIENT_ID', default='')
MARKETING_INSTAGRAM_CLIENT_SECRET = env('MARKETING_INSTAGRAM_CLIENT_SECRET', default='')
MARKETING_INSTAGRAM_REDIRECT_URI = env('MARKETING_INSTAGRAM_REDIRECT_URI', default='')
LINKEDIN_API_BASE_URL = env('LINKEDIN_API_BASE_URL', default='https://api.linkedin.com')
LINKEDIN_API_VERSION = env('LINKEDIN_API_VERSION', default='202606')
BACKOFFICE_LINKEDIN_CLIENT_ID = env('BACKOFFICE_LINKEDIN_CLIENT_ID', default='')
BACKOFFICE_LINKEDIN_CLIENT_SECRET = env('BACKOFFICE_LINKEDIN_CLIENT_SECRET', default='')
BACKOFFICE_LINKEDIN_REDIRECT_URI = env('BACKOFFICE_LINKEDIN_REDIRECT_URI', default='')
BACKOFFICE_LINKEDIN_SCOPES = env(
    'BACKOFFICE_LINKEDIN_SCOPES',
    default='openid profile w_member_social',
)
BACKOFFICE_LINKEDIN_ORGANIZATION_URNS = env('BACKOFFICE_LINKEDIN_ORGANIZATION_URNS', default='')
LINKEDIN_CLIENT_ID = env('LINKEDIN_CLIENT_ID', default='')
LINKEDIN_CLIENT_SECRET = env('LINKEDIN_CLIENT_SECRET', default='')
LINKEDIN_REDIRECT_URI = env('LINKEDIN_REDIRECT_URI', default=BACKOFFICE_LINKEDIN_REDIRECT_URI)
LINKEDIN_SCOPES = env('LINKEDIN_SCOPES', default=BACKOFFICE_LINKEDIN_SCOPES)
LINKEDIN_ORGANIZATION_URNS = env(
    'LINKEDIN_ORGANIZATION_URNS',
    default=BACKOFFICE_LINKEDIN_ORGANIZATION_URNS,
)
INSTAGRAM_GRAPH_API_BASE_URL = env(
    'INSTAGRAM_GRAPH_API_BASE_URL',
    default='https://graph.instagram.com',
)
INSTAGRAM_GRAPH_API_VERSION = env(
    'INSTAGRAM_GRAPH_API_VERSION',
    default=META_GRAPH_API_VERSION,
)
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_REDIRECT_URI = env('GOOGLE_REDIRECT_URI', default='')
MARKETING_GOOGLE_REDIRECT_URI = env('MARKETING_GOOGLE_REDIRECT_URI', default='')
BACKOFFICE_YOUTUBE_CLIENT_ID = env('BACKOFFICE_YOUTUBE_CLIENT_ID', default='')
BACKOFFICE_YOUTUBE_CLIENT_SECRET = env('BACKOFFICE_YOUTUBE_CLIENT_SECRET', default='')
BACKOFFICE_YOUTUBE_REDIRECT_URI = env('BACKOFFICE_YOUTUBE_REDIRECT_URI', default='')
BACKOFFICE_YOUTUBE_SCOPES = env('BACKOFFICE_YOUTUBE_SCOPES', default='')
BACKOFFICE_YOUTUBE_DEFAULT_PRIVACY = env(
    'BACKOFFICE_YOUTUBE_DEFAULT_PRIVACY',
    default='private',
)
BACKOFFICE_YOUTUBE_CATEGORY_ID = env('BACKOFFICE_YOUTUBE_CATEGORY_ID', default='28')
BACKOFFICE_YOUTUBE_UPLOAD_TIMEOUT = env.int('BACKOFFICE_YOUTUBE_UPLOAD_TIMEOUT', default=900)
BACKOFFICE_MARKETING_IMAGE_MAX_BYTES = env.int(
    'BACKOFFICE_MARKETING_IMAGE_MAX_BYTES',
    default=15 * 1024 * 1024,
)
BACKOFFICE_MARKETING_VIDEO_MAX_BYTES = env.int(
    'BACKOFFICE_MARKETING_VIDEO_MAX_BYTES',
    default=512 * 1024 * 1024,
)
TIKTOK_CLIENT_KEY = env('TIKTOK_CLIENT_KEY', default='')
TIKTOK_CLIENT_SECRET = env('TIKTOK_CLIENT_SECRET', default='')
TIKTOK_REDIRECT_URI = env('TIKTOK_REDIRECT_URI', default='')
MARKETING_TIKTOK_REDIRECT_URI = env('MARKETING_TIKTOK_REDIRECT_URI', default='')
BACKOFFICE_TIKTOK_CLIENT_KEY = env('BACKOFFICE_TIKTOK_CLIENT_KEY', default='')
BACKOFFICE_TIKTOK_CLIENT_SECRET = env('BACKOFFICE_TIKTOK_CLIENT_SECRET', default='')
BACKOFFICE_TIKTOK_REDIRECT_URI = env('BACKOFFICE_TIKTOK_REDIRECT_URI', default='')
BACKOFFICE_TIKTOK_SCOPES = env(
    'BACKOFFICE_TIKTOK_SCOPES',
    default='user.info.basic video.list video.upload video.publish',
)
BACKOFFICE_TIKTOK_DEFAULT_PRIVACY = env(
    'BACKOFFICE_TIKTOK_DEFAULT_PRIVACY',
    default='SELF_ONLY',
)
BACKOFFICE_TIKTOK_UPLOAD_TIMEOUT = env.int(
    'BACKOFFICE_TIKTOK_UPLOAD_TIMEOUT',
    default=900,
)
MERCADO_LIBRE_WEBHOOK_SECRET = env('MERCADO_LIBRE_WEBHOOK_SECRET', default='')
RENTA_ESPACIOS_SYNC_TOKEN = env('RENTA_ESPACIOS_SYNC_TOKEN', default='')
FINANZAS_CXC_SYNC_TOKEN = env('FINANZAS_CXC_SYNC_TOKEN', default='')
SMOKE_REPORT_TOKEN = env('SMOKE_REPORT_TOKEN', default='')
