# Generated by Django 6.0.4 on 2026-09-12 18:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('crm', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=40, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('metodo', models.CharField(choices=[('SPEI', 'Transferencia SPEI'), ('TARJETA', 'Tarjeta'), ('BILLETERA', 'Billetera digital')], default='SPEI', max_length=20)),
                ('qr_payload', models.TextField(blank=True, default='', help_text='Contenido que codifica el QR; el cliente lo renderiza en pantalla.')),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cobro QR',
                'verbose_name_plural': 'Cobros QR',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_servicio', models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('RESTAURANTE', 'Restaurante')], default='MOSTRADOR', max_length=20)),
                ('acepta_cobro_qr', models.BooleanField(default=True)),
                ('menu_qr_activo', models.BooleanField(default=False, help_text='Publica el menu por codigo QR para los comensales.')),
                ('menu_token', models.CharField(blank=True, max_length=32, unique=True)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('porcentaje_propina_sugerido', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(help_text='Bodega contra la que descuenta inventario esta caja.', on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='catalogo.bodega')),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='empresas.capanegocio')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_venta', to='empresas.entidadnegocio')),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('zona', models.CharField(blank=True, default='', max_length=60)),
                ('capacidad', models.PositiveSmallIntegerField(default=4)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('CUENTA', 'Cuenta solicitada')], default='LIBRE', max_length=20)),
                ('qr_token', models.CharField(blank=True, max_length=32, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='pos.puntoventa')),
            ],
            options={
                'ordering': ['zona', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('COBRADO', 'Cobrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20)),
                ('tipo_servicio', models.CharField(choices=[('COMER_AQUI', 'Comer aqui'), ('PARA_LLEVAR', 'Para llevar'), ('DOMICILIO', 'A domicilio')], default='COMER_AQUI', max_length=20)),
                ('origen', models.CharField(choices=[('CAJA', 'Caja'), ('MENU_QR', 'Menu QR')], default='CAJA', max_length=20)),
                ('comensales', models.PositiveSmallIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True)),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_pos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_pos', to='empresas.capanegocio')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_pos', to='crm.cliente')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='pos.mesa')),
                ('orden', models.OneToOneField(blank=True, help_text='Orden de catalogo creada al cobrar, para mover inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_pos', to='catalogo.orden')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='pos.puntoventa')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('QR', 'Cobro QR'), ('TRANSFERENCIA', 'Transferencia'), ('CORTESIA', 'Cortesia')], default='EFECTIVO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibido', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo entregado por el cliente, para calcular el cambio.', max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cobro_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pos.cobroqr')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pos', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pos.ticket')),
            ],
            options={
                'verbose_name': 'Pago de ticket',
                'verbose_name_plural': 'Pagos de ticket',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cobroqr',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_qr', to='pos.ticket'),
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparacion'), ('SERVIDO', 'Servido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.CharField(blank=True, default='', help_text='Indicaciones para cocina: sin cebolla, termino medio, etc.', max_length=240)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='catalogo.producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.ticket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado al cierre; se compara contra lo esperado.', max_digits=12, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('corte', models.JSONField(blank=True, default=dict, help_text='Corte congelado al cerrar: totales por forma de pago y diferencia.')),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_pos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_pos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pos.puntoventa')),
            ],
            options={
                'ordering': ['-fecha_apertura', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='pos.turno'),
        ),
        migrations.AddIndex(
            model_name='puntoventa',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_pos_pv_capa_activo'),
        ),
        migrations.AddIndex(
            model_name='puntoventa',
            index=models.Index(fields=['capa_negocio', 'codigo'], name='idx_pos_pv_capa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='puntoventa',
            constraint=models.UniqueConstraint(fields=('capa_negocio', 'codigo'), name='unique_pos_punto_venta_por_capa'),
        ),
        migrations.AddIndex(
            model_name='mesa',
            index=models.Index(fields=['punto_venta', 'estado'], name='idx_pos_mesa_pv_estado'),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('punto_venta', 'nombre'), name='unique_pos_mesa_por_punto_venta'),
        ),
        migrations.AddIndex(
            model_name='pagoticket',
            index=models.Index(fields=['ticket', 'forma'], name='idx_pos_pago_tkt_forma'),
        ),
        migrations.AddIndex(
            model_name='cobroqr',
            index=models.Index(fields=['ticket', 'estado'], name='idx_pos_qr_tkt_estado'),
        ),
        migrations.AddIndex(
            model_name='cobroqr',
            index=models.Index(fields=['estado', 'expira_en'], name='idx_pos_qr_estado_exp'),
        ),
        migrations.AddIndex(
            model_name='ticketitem',
            index=models.Index(fields=['ticket', 'estado'], name='idx_pos_tktitem_estado'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['punto_venta', 'estado'], name='idx_pos_turno_pv_estado'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('punto_venta',), name='unique_pos_turno_abierto_por_caja'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['capa_negocio', 'estado'], name='idx_pos_tkt_capa_estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['punto_venta', 'estado'], name='idx_pos_tkt_pv_estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['turno'], name='idx_pos_tkt_turno'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('punto_venta', 'folio'), name='unique_pos_folio_por_punto_venta'),
        ),
    ]
