# Generated by Django 6.0.4 on 2026-09-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('FULFILLMENT', 'Fulfillment'), ('VIRTUAL', 'Virtual')], default='INTERNA', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresas.capanegocio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reservado', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ultimo_costo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_items', to='catalogo.bodega')),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_items', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['producto__nombre', 'bodega__nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('POS_QR', 'Punto de venta QR')], default='POS_QR', max_length=40)),
                ('external_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('estatus', models.CharField(choices=[('NUEVA', 'Nueva'), ('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ERROR', 'Error')], default='NUEVA', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('REEMBOLSADA', 'Reembolsada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=180)),
                ('cliente_email', models.EmailField(blank=True, default='', max_length=254)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=40)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='empresas.capanegocio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sku', models.CharField(max_length=100)),
                ('brand_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=120, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('master_attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('amazon', 'Amazon'), ('mercado_libre', 'Mercado Libre'), ('ingram', 'Ingram API'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], default='manual', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.capanegocio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(blank=True, default='', max_length=120)),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_items', to='catalogo.bodega')),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_items', to='empresas.capanegocio')),
                ('inventario_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_items', to='catalogo.inventarioitem')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='catalogo.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolucion'), ('CANCELACION', 'Cancelacion'), ('PERDIDA', 'Perdida'), ('RESERVA', 'Reserva'), ('LIBERACION', 'Liberacion'), ('SYNC_IMPORT', 'Sync import')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_nuevo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('referencia_tipo', models.CharField(blank=True, default='', max_length=80)),
                ('referencia_id', models.CharField(blank=True, default='', max_length=120)),
                ('nota', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_movimientos', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_movimientos', to='catalogo.bodega')),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_movimientos', to='empresas.capanegocio')),
                ('evento_auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_movimientos', to='accounts.eventoauditoria')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='catalogo.inventarioitem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_movimientos', to='catalogo.producto')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_items', to='catalogo.producto'),
        ),
        migrations.CreateModel(
            name='CalidadIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(blank=True, default='', max_length=60)),
                ('external_resource_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_code', models.CharField(blank=True, default='', max_length=120)),
                ('issue_type', models.CharField(choices=[('ATRIBUTO_FALTANTE', 'Atributo faltante'), ('CATEGORIA', 'Categoria'), ('IMAGEN', 'Imagen'), ('COPY', 'Copy'), ('PRECIO', 'Precio'), ('PUBLICACION_RECHAZADA', 'Publicacion rechazada'), ('OTRO', 'Otro')], default='PUBLICACION_RECHAZADA', max_length=40)),
                ('prioridad', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn'), ('BLOCKER', 'Blocker')], default='WARN', max_length=20)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revision'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='ABIERTA', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('raw_error', models.TextField(blank=True, default='')),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=dict)),
                ('ai_assisted', models.BooleanField(default=True)),
                ('requiere_revision_humana', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calidad_asignadas', to=settings.AUTH_USER_MODEL)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_incidencias', to='empresas.capanegocio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calidad_creadas', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calidad_resueltas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calidad_incidencias', to='catalogo.producto')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogo/productos/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('public_url', models.URLField(blank=True, default='', max_length=500)),
                ('asset_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('content_type', models.CharField(blank=True, default='', max_length=80)),
                ('bytes_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bodega',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_vf_bod_capa_activo'),
        ),
        migrations.AddIndex(
            model_name='bodega',
            index=models.Index(fields=['capa_negocio', 'codigo'], name='idx_vf_bod_capa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('capa_negocio', 'codigo'), name='unique_vf_warehouse_code_per_capa'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_vf_cat_capa_activo'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['parent', 'nombre'], name='idx_vf_cat_parent_nombre'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('capa_negocio', 'nombre'), name='unique_vf_root_category_per_capa'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('capa_negocio', 'parent', 'nombre'), name='unique_vf_child_category_per_parent'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['capa_negocio', 'estatus'], name='idx_vf_ord_capa_estado'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['capa_negocio', 'canal'], name='idx_vf_ord_capa_canal'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['external_order_id'], name='idx_vf_ord_external'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_creacion'], name='idx_vf_ord_fecha'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id', ''), _negated=True), fields=('capa_negocio', 'canal', 'external_order_id'), name='unique_vf_order_external_per_capa'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_vf_prod_capa_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['capa_negocio', 'marca'], name='idx_vf_prod_capa_marca'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['capa_negocio', 'categoria'], name='idx_vf_prod_capa_cat'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('capa_negocio', 'internal_sku'), name='unique_vf_sku_per_capa'),
        ),
        migrations.AddIndex(
            model_name='ordenitem',
            index=models.Index(fields=['capa_negocio', 'producto'], name='idx_vf_ordit_capa_prod'),
        ),
        migrations.AddIndex(
            model_name='ordenitem',
            index=models.Index(fields=['orden', 'producto'], name='idx_vf_ordit_order_prod'),
        ),
        migrations.AddIndex(
            model_name='ordenitem',
            index=models.Index(fields=['external_item_id'], name='idx_vf_ordit_external'),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['capa_negocio', 'fecha_creacion'], name='idx_vf_mov_capa_fecha'),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['capa_negocio', 'tipo'], name='idx_vf_mov_capa_tipo'),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['producto', 'bodega'], name='idx_vf_mov_prod_bod'),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['referencia_tipo', 'referencia_id'], name='idx_vf_mov_ref'),
        ),
        migrations.AddIndex(
            model_name='inventarioitem',
            index=models.Index(fields=['capa_negocio', 'producto'], name='idx_vf_inv_capa_prod'),
        ),
        migrations.AddIndex(
            model_name='inventarioitem',
            index=models.Index(fields=['capa_negocio', 'bodega'], name='idx_vf_inv_capa_bod'),
        ),
        migrations.AddConstraint(
            model_name='inventarioitem',
            constraint=models.UniqueConstraint(fields=('capa_negocio', 'producto', 'bodega'), name='unique_vf_inventory_item_per_capa'),
        ),
        migrations.AddIndex(
            model_name='calidadincidencia',
            index=models.Index(fields=['capa_negocio', 'estatus'], name='idx_vf_cal_capa_estado'),
        ),
        migrations.AddIndex(
            model_name='calidadincidencia',
            index=models.Index(fields=['capa_negocio', 'canal'], name='idx_vf_cal_capa_canal'),
        ),
        migrations.AddIndex(
            model_name='calidadincidencia',
            index=models.Index(fields=['producto', 'estatus'], name='idx_vf_cal_prod_estado'),
        ),
        migrations.AddIndex(
            model_name='calidadincidencia',
            index=models.Index(fields=['external_code'], name='idx_vf_cal_external_code'),
        ),
        migrations.AddIndex(
            model_name='productoimagen',
            index=models.Index(fields=['producto', 'asset_status'], name='idx_vf_img_prod_status'),
        ),
        migrations.AddConstraint(
            model_name='productoimagen',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('producto',), name='unique_vf_main_image_per_product'),
        ),
    ]
