# Generated by Django 6.0.4 on 2026-09-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_persona_moral', models.BooleanField(default=False)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('razon_social', models.CharField(help_text='Nombre o Razón Social tal cual en la CSF', max_length=250)),
                ('rfc', models.CharField(max_length=13)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=150, null=True)),
                ('regimenes_fiscales_detectados', models.JSONField(blank=True, null=True)),
                ('regimen_fiscal_pendiente_seleccion', models.BooleanField(default=False)),
                ('identificador', models.CharField(blank=True, help_text='ID Interno opcional', max_length=100, null=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_csf_url', models.URLField(blank=True, help_text='URL pública o firmada del PDF en Cloudflare R2', max_length=500, null=True)),
                ('contrato_digital_url', models.URLField(blank=True, help_text='URL del contrato digital del cliente en R2', max_length=500, null=True)),
                ('contrato_digital_nombre', models.CharField(blank=True, help_text='Nombre original del archivo de contrato', max_length=255, null=True)),
                ('correo_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_pais', models.CharField(default='+52', max_length=10)),
                ('telefono', models.CharField(help_text='Crucial para validación de pagos en Make/WhatsApp', max_length=20)),
                ('pais', models.CharField(default='México', max_length=50)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=150, null=True)),
                ('calle', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('agente_cobranza', models.CharField(blank=True, max_length=150, null=True)),
                ('dia_corte_individual', models.IntegerField(blank=True, help_text='Obligatorio si la entidad usa corte INDIVIDUAL (1-31)', null=True)),
                ('dias_gracia', models.IntegerField(default=0, help_text='Días de tolerancia antes de recargos')),
                ('consentimiento_cobranza_aceptado', models.BooleanField(default=False)),
                ('consentimiento_cobranza_fecha', models.DateTimeField(blank=True, null=True)),
                ('consentimiento_cobranza_version', models.CharField(blank=True, max_length=30, null=True)),
                ('consentimiento_cobranza_texto_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('consentimiento_cobranza_metadata', models.JSONField(blank=True, null=True)),
                ('no_contactar_cobranza', models.BooleanField(default=False)),
                ('no_contactar_cobranza_motivo', models.CharField(blank=True, max_length=240, null=True)),
                ('no_contactar_cobranza_fecha', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entidad_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.entidadnegocio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es indefinido', null=True)),
                ('cliente_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_contratados', to='crm.cliente')),
                ('regla_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.reglanegocio')),
            ],
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['entidad_relacionada', 'activo'], name='idx_cliente_ent_activo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['entidad_relacionada', 'identificador'], name='idx_cliente_ent_ident'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['entidad_relacionada', 'telefono'], name='idx_cliente_ent_tel'),
        ),
    ]
