# Generated by Django 6.0.4 on 2026-09-12 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('crm', '0001_initial'),
        ('empresas', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaEmitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('BACKOFFICE_SAAS', 'Backoffice SaaS'), ('CLIENTE_CXC', 'Cliente CxC'), ('PORTAL_CLIENTE', 'Portal cliente'), ('MANUAL', 'Manual')], max_length=30)),
                ('proveedor', models.CharField(choices=[('FACTURAMA', 'Facturama'), ('FACTURAPI', 'Facturapi'), ('FISCALAPI', 'FiscalAPI'), ('FINKOK', 'Finkok'), ('SW', 'SW Sapien'), ('OTRO', 'Otro')], default='FACTURAMA', max_length=30)),
                ('modo', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Produccion')], default='SANDBOX', max_length=20)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('TIMBRADA', 'Timbrada'), ('ERROR', 'Error'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(blank=True, max_length=60, null=True)),
                ('uuid', models.CharField(blank=True, max_length=80, null=True)),
                ('proveedor_factura_id', models.CharField(blank=True, max_length=160, null=True)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('tipo_comprobante', models.CharField(default='I', max_length=5)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('emisor_rfc', models.CharField(max_length=13)),
                ('emisor_razon_social', models.CharField(max_length=220)),
                ('emisor_regimen_fiscal', models.CharField(max_length=20)),
                ('receptor_rfc', models.CharField(max_length=13)),
                ('receptor_razon_social', models.CharField(max_length=220)),
                ('receptor_regimen_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('receptor_codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('receptor_uso_cfdi', models.CharField(default='G03', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('payload_proveedor', models.JSONField(blank=True, null=True)),
                ('respuesta_proveedor', models.JSONField(blank=True, null=True)),
                ('error_proveedor', models.TextField(blank=True, null=True)),
                ('xml_url', models.URLField(blank=True, max_length=700, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=700, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capa_emisora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to='empresas.capanegocio')),
                ('cliente_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_recibidas', to='crm.cliente')),
                ('cuenta_por_cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to='finanzas.cuentaporcobrar')),
                ('pago_cxc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to='finanzas.pagocuentaporcobrar')),
                ('suscripcion_saas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to='billing.suscripcioncapa')),
            ],
            options={
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('clave_producto_servicio', models.CharField(max_length=20)),
                ('clave_unidad', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('objeto_impuesto', models.CharField(default='01', max_length=5)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='facturacion.facturaemitida')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoSelloDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('FACTURAMA', 'Facturama'), ('FACTURAPI', 'Facturapi'), ('FISCALAPI', 'FiscalAPI'), ('FINKOK', 'Finkok'), ('SW', 'SW Sapien'), ('OTRO', 'Otro')], default='FACTURAMA', max_length=30)),
                ('modo', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Produccion')], default='SANDBOX', max_length=20)),
                ('rfc', models.CharField(max_length=13)),
                ('certificado_url', models.URLField(blank=True, max_length=700, null=True)),
                ('llave_url', models.URLField(blank=True, max_length=700, null=True)),
                ('llave_password_encrypted', models.TextField(blank=True, null=True)),
                ('numero_certificado', models.CharField(blank=True, max_length=80, null=True)),
                ('valido_desde', models.DateTimeField(blank=True, null=True)),
                ('valido_hasta', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('ERROR', 'Error'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=20)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_facturacion', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['-activo', '-actualizado_en', '-id'],
                'indexes': [models.Index(fields=['capa_negocio', 'proveedor', 'modo'], name='idx_csd_capa_prov_modo')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('capa_negocio', 'proveedor', 'modo'), name='uniq_csd_activo_capa_prov')],
            },
        ),
        migrations.AddIndex(
            model_name='facturaemitida',
            index=models.Index(fields=['capa_emisora', 'contexto', 'estatus'], name='idx_fact_capa_ctx_estatus'),
        ),
        migrations.AddIndex(
            model_name='facturaemitida',
            index=models.Index(fields=['uuid'], name='idx_fact_uuid'),
        ),
    ]
