# Generated by Django 6.0.4 on 2026-09-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('tipo_capa', models.CharField(choices=[('ADMINISTRADORA', 'Administradora'), ('EMPRESA', 'Empresa'), ('HOTEL', 'Hotel'), ('GRUPO', 'Grupo'), ('OPERADORA', 'Operadora')], default='OPERADORA', max_length=20)),
                ('nombre_administrador', models.CharField(blank=True, max_length=150, null=True)),
                ('es_persona_moral', models.BooleanField(default=True)),
                ('razon_social', models.CharField(blank=True, max_length=180, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pais_fiscal', models.CharField(default='Mexico', max_length=80)),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_fiscal', models.CharField(blank=True, max_length=120, null=True)),
                ('colonia_fiscal', models.CharField(blank=True, max_length=120, null=True)),
                ('calle_fiscal', models.CharField(blank=True, max_length=180, null=True)),
                ('numero_exterior_fiscal', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_interior_fiscal', models.CharField(blank=True, max_length=40, null=True)),
                ('facturacion_activa', models.BooleanField(default=False)),
                ('facturacion_modo', models.CharField(choices=[('MANUAL', 'Manual'), ('SANDBOX', 'PAC Sandbox'), ('PRODUCCION', 'PAC Produccion')], default='MANUAL', max_length=20)),
                ('facturacion_pac_proveedor', models.CharField(choices=[('SIN_PROVEEDOR', 'Sin proveedor'), ('FACTURAMA', 'Facturama'), ('FACTURAPI', 'Facturapi'), ('FISCALAPI', 'FiscalAPI'), ('FINKOK', 'Finkok'), ('SW', 'SW Sapien'), ('OTRO', 'Otro')], default='SIN_PROVEEDOR', max_length=30)),
                ('facturacion_serie_ingresos', models.CharField(default='A', max_length=10)),
                ('facturacion_lugar_expedicion', models.CharField(blank=True, max_length=10, null=True)),
                ('facturacion_producto_servicio', models.CharField(blank=True, max_length=20, null=True)),
                ('facturacion_unidad', models.CharField(default='E48', max_length=20)),
                ('facturacion_uso_cfdi_default', models.CharField(default='G03', max_length=10)),
                ('facturacion_metodo_pago_default', models.CharField(default='PUE', max_length=10)),
                ('facturacion_forma_pago_default', models.CharField(default='03', max_length=10)),
                ('portal_clientes_activo', models.BooleanField(default=False)),
                ('portal_clientes_url_base', models.URLField(blank=True, max_length=500, null=True)),
                ('seguridad_doble_factor_activa', models.BooleanField(default=False)),
                ('clabe_transferencias', models.CharField(blank=True, max_length=18, null=True)),
                ('banco_transferencias', models.CharField(blank=True, max_length=80, null=True)),
                ('beneficiario_transferencias', models.CharField(blank=True, max_length=180, null=True)),
                ('referencia_transferencia_prefijo', models.CharField(default='BETT', max_length=20)),
                ('plazo_meses_default', models.PositiveSmallIntegerField(default=12)),
                ('periodicidad_cobro_default', models.CharField(choices=[('UNICO', 'Cobro Unico'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('fecha_vencimiento_modo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GLOBAL', 'Misma fecha para todos'), ('INDIVIDUAL', 'Fecha individual por cliente')], default='PENDIENTE', max_length=20)),
                ('dia_vencimiento_default', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_gracia_default', models.PositiveSmallIntegerField(default=0)),
                ('auto_renueva_default', models.BooleanField(default=False)),
                ('aplicacion_pagos', models.CharField(choices=[('ADEUDO_MAS_ANTIGUO', 'Adeudo mas antiguo'), ('SALDO_A_FAVOR', 'Conservar saldo a favor')], default='ADEUDO_MAS_ANTIGUO', max_length=25)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_fundador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_fundadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_fecha_corte', models.CharField(choices=[('GENERAL', 'General (Ej. Condominios)'), ('INDIVIDUAL', 'Individual (Ej. Aniversario)')], default='INDIVIDUAL', max_length=20)),
                ('dia_corte_general', models.IntegerField(blank=True, help_text='Solo si el corte es GENERAL (1-31)', null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pausa', models.DateField(blank=True, help_text='Fecha en que se detuvo la operacion/cobranza', null=True)),
                ('capa_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='ReglaMarcoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Interes moratorio, deposito, poliza juridica', max_length=150)),
                ('tipo_calculo', models.CharField(choices=[('CARGO_FIJO', 'Cargo Fijo ($)'), ('DESCUENTO_FIJO', 'Descuento Fijo (-$)'), ('PORCENTAJE_RECARGO', 'Porcentaje de Recargo (+)'), ('PORCENTAJE_DESCUENTO', 'Porcentaje de Descuento (-)')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad', models.CharField(choices=[('UNICO', 'Cobro Unico'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('aplica_a_todos', models.BooleanField(default=False)),
                ('dias_condicion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_marco', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Cuota Mantenimiento, Mejora Fachada, Penalizacion', max_length=150)),
                ('tipo_calculo', models.CharField(choices=[('CARGO_FIJO', 'Cargo Fijo ($)'), ('DESCUENTO_FIJO', 'Descuento Fijo (-$)'), ('PORCENTAJE_RECARGO', 'Porcentaje de Recargo (+)'), ('PORCENTAJE_DESCUENTO', 'Porcentaje de Descuento (-)')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Monto fijo o porcentaje (ej. 5.0 para 5%)', max_digits=10)),
                ('periodicidad', models.CharField(choices=[('UNICO', 'Cobro Unico'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('aplica_a_todos', models.BooleanField(default=False, help_text='Si es True, se genera el cobro automaticamente a todos los clientes.')),
                ('dias_condicion', models.IntegerField(blank=True, help_text='Usar 3 para atraso o -5 para pronto pago.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_dinamicas', to='empresas.entidadnegocio')),
                ('regla_marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_personalizadas', to='empresas.reglamarconegocio')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BackupCapaExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=240)),
                ('storage_backend', models.CharField(default='LOCAL', max_length=30)),
                ('bucket', models.CharField(blank=True, max_length=180, null=True)),
                ('object_key', models.CharField(blank=True, max_length=500, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('estatus', models.CharField(choices=[('GENERADO', 'Generado'), ('ERROR', 'Error')], default='GENERADO', max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('generado_por', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('capa_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups_exportados', to='empresas.capanegocio')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['capa_negocio', 'fecha_creacion'], name='idx_backup_capa_fecha'), models.Index(fields=['storage_backend', 'estatus'], name='idx_backup_storage_est')],
            },
        ),
        migrations.AddIndex(
            model_name='entidadnegocio',
            index=models.Index(fields=['capa_negocio', 'activo'], name='idx_entidad_capa_activo'),
        ),
        migrations.AddConstraint(
            model_name='entidadnegocio',
            constraint=models.UniqueConstraint(condition=models.Q(('capa_negocio__isnull', False)), fields=('capa_negocio', 'nombre_comercial'), name='unique_entidad_nombre_por_capa'),
        ),
        migrations.AddConstraint(
            model_name='entidadnegocio',
            constraint=models.UniqueConstraint(condition=models.Q(('capa_negocio__isnull', True)), fields=('nombre_comercial',), name='unique_entidad_nombre_sin_capa'),
        ),
        migrations.AddConstraint(
            model_name='reglamarconegocio',
            constraint=models.UniqueConstraint(fields=('capa_negocio', 'nombre'), name='unique_regla_marco_por_capa_y_nombre'),
        ),
        migrations.AddConstraint(
            model_name='reglanegocio',
            constraint=models.UniqueConstraint(condition=models.Q(('regla_marco__isnull', False)), fields=('entidad', 'regla_marco'), name='unique_override_por_entidad_y_regla_marco'),
        ),
    ]
